'use client'

import { usePathname } from 'next/navigation';
import { useState } from 'react';
import './style.css';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [input, setInput] = useState('');
  const pathname = usePathname();

  return (
    <div>
      <h1>Hello World</h1>
      <div>
        <input type="text" value={input} onChange={(e) => setInput(e.target.value)} className="border-2 border-gray-300 rounded-md p-2" />
        <p>Pathname: {pathname}</p>
      </div>
      {children}
    </div>
  )
}
