'use client'

import './globals.css'
import { ThemeProvider } from './_components/ThemeProvider'
import { SimpleThemeToggle } from './_components/ThemeToggle'
import { usePathname } from "next/navigation";
import Link from 'next/link';

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

const navLinks = [
  {name: 'Register', href: '/register'},
  {name: 'Login', href: '/login'},
  {name: 'Dashboard', href: '/dashboard'},
  {name: 'Products', href: '/products'},
  {name: 'Blog', href: '/blog'},
  {name: 'Forgot Password', href: '/forgot-password'},
  {name: 'Tailwind Test', href: '/tailwind-test'},
  {name: 'Reset vs Reload', href: '/reset-vs-reload-demo'},
]

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();

  return (
    <html lang="en">
      <body className="bg-gray-100 dark:bg-gray-900">
        <ThemeProvider>
          <header className="bg-blue-500 dark:bg-blue-800 p-4 text-white">
            <div className="flex justify-between items-center">
              <nav>
                {navLinks.map((link) => {
                  const isActive = pathname === link.href || (pathname.startsWith(link.href) && link.href !== '/');
                  return (
                    <Link key={link.href} href={link.href} className={`${isActive ? 'font-bold mr-4' : 'mr-4 text-blue-500'}`}>
                      {link.name}
                    </Link>
                  )
                })}
              </nav>
              <SimpleThemeToggle />
            </div>
          </header>
          <main className="p-4 bg-white dark:bg-gray-800 text-gray-900 dark:text-gray-100 min-h-screen">
            {children}
          </main>
          <footer className="bg-gray-800 dark:bg-gray-900 text-white p-4 text-center">
            <p>Footer</p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  )
}

